Write a Python Program to Add Two Matrices?

In [3]:
import numpy as np

In [4]:
A = [[1,2,3], 
    [4,5,6],
    [7,8,9]]

In [5]:
B = [[9, 5, 7],
     [6, 5, 4],
     [3, 2, 1]]

In [6]:

matrix = np.array(A) + np.array(B)
matrix

array([[10,  7, 10],
       [10, 10, 10],
       [10, 10, 10]])

In [7]:
matrix = np.array(A) + np.array(B)
matrix

array([[10,  7, 10],
       [10, 10, 10],
       [10, 10, 10]])

Write a Python Program to Multiply Two Matrices?

In [8]:
A = [[1,2,3], 
    [4,5,6],
    [7,8,9]]

In [9]:
B = [[9, 5, 7],
     [6, 5, 4],
     [3, 2, 1]]

In [12]:
matrix = np.dot(A,B)
matrix

array([[ 30,  21,  18],
       [ 84,  57,  54],
       [138,  93,  90]])

Write a Python Program to Transpose a Matrix?

In [ ]:
B = [[9, 5, 7],
     [6, 5, 4],
     [3, 2, 1]]

In [13]:
a = np.transpose(B)

In [14]:
a

array([[9, 6, 3],
       [5, 5, 2],
       [7, 4, 1]])

Write a Python Program to Sort Words in Alphabetic Order?

In [15]:
my_str = input("Enter a string: ")
words = [word.lower() for word in my_str.split()]

words.sort()
print("The sorted words are:")
for word in words:
    print(word)

Enter a string: Hello world Is beautifull
The sorted words are:
beautifull
hello
is
world


Write a Python Program to Remove Punctuation From a String?

In [16]:
punctuations = '''!()-[]{};:'"\,<>./?@#$%^&*_~'''
my_str = input("Enter a string: ")

no_punct = ""
for char in my_str:
    if char not in punctuations:
        no_punct = no_punct + char
print(no_punct)


Enter a string: Hello! welcome to Goa, Singham ...
Hello welcome to Goa Singham 
